-- Basic auditing for item lifecycle actions from the app.

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('item_created', 'item_deleted')),
  entity_type text not null default 'item',
  entity_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_audit_events_user_created_at
  on public.audit_events (user_id, created_at desc);

create index if not exists idx_audit_events_entity
  on public.audit_events (entity_type, entity_id);

alter table public.audit_events enable row level security;

drop policy if exists "Users can insert own audit events" on public.audit_events;
create policy "Users can insert own audit events"
  on public.audit_events
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own audit events" on public.audit_events;
create policy "Users can read own audit events"
  on public.audit_events
  for select
  to authenticated
  using (auth.uid() = user_id);
