-- Apple In-App Purchase integration scaffolding ------------------------------

-- Link billing plans to Apple product identifiers + App Store listing URLs
-- so we can cross-reference receipts from the App Store Server API.
alter table public.billing_plans
  add column if not exists apple_product_id text unique,
  add column if not exists appstore_listing_url text;

-- When limits are enforced we snapshot the billing plan details next to each
-- counter entry; add a JSONB column for plan metadata.
alter table public.usage_counters
  add column if not exists plan_snapshot jsonb default '{}'::jsonb;

-- Track billing events/webhooks (Apple server notifications) for auditing.
create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  payload jsonb not null,
  source text default 'apple',
  created_at timestamptz default timezone('utc', now())
);

alter table public.billing_events enable row level security;

create policy "Users can view their own billing events"
  on public.billing_events
  for select
  using (auth.uid() = user_id);
